name: Build + release PR branch to dev

on:
  pull_request:
    branches: [ main ]

jobs:

  build-piano:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
   
    - name: Test Docker build
      id: build-image
      working-directory: ./piano-io
      run: |
        docker build .
