name: Test Android Pull Requests

on:
  pull_request:
    paths:
      - 'android/**'

  push:
    branches: [ main ]
    paths:
      - 'android/**'

  # This allows us to manually run this job
  workflow_dispatch:

jobs:

  kotlin-code-checks:
    name: Code Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle (Mobile)
        working-directory: android/mobile
        run: ./gradlew build

      - name: Build with Gradle (TV Custom)
        working-directory: android/tv-custom
        run: ./gradlew build

      - name: Build with Gradle (TV Device Auth Grant)
        working-directory: android/tv-device-auth-grant
        run: ./gradlew build
