name: Test iOS Pull Requests

on:
  pull_request:
    paths:
      - 'ios/**'

  push:
    branches: [ main ]
    paths:
      - 'ios/**'

  # This allows us to manually run this job
  workflow_dispatch:

jobs:

  swift-code-checks:
    name: Code Tests
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Build mobile sample with xcodebuild
        run: xcodebuild -project ios/mobile/OpenPass-Sample-iOS.xcodeproj -scheme OpenPass-Sample-iOS build 

      - name: Build tv sample with xcodebuild
        run: xcodebuild -project ios/tv-device-auth-grant/OpenPass-Sample-tvOS.xcodeproj -scheme OpenPass-Sample-tvOS build
